version: "3"

services:
  mc-bukkit:
    container_name: mc-bukkit
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    volumes:
      - "./mc/mc-bukkit:/data"
      - "./plugins/1.14.4-R0.1-SNAPSHOT:/data/plugins"
      - "./assets:/data/assets"
    environment:
      OVERRIDE_SERVER_PROPERTIES: "true"
      EULA: "TRUE"
      ONLINE_MODE: "FALSE"
      INIT_MEMORY: "1G"
      MAX_MEMORY: "4G"
      SERVER_NAME: "mc-bukkit"
      SERVER_PORT: 25565
      MOTD: "Check ServerListPlus plugin"
      TYPE: "BUKKIT"
      VERSION: "1.14.4-R0.1-SNAPSHOT"
      OPS: "purplepant1es"
      ICON: "/data/assets/icon.png"
      MAX_PLAYERS: "5"
      DIFFICULTY: "peaceful"
      MODE: "survival"
      VIEW_DISTANCE: 8
      FORCE_GAMEMODE: "true"
      ALLOW_NETHER: "true"
      HARDCORE: "false"
      SNOOPER_ENABLED: "false"
      PVP: "false"
      LEVEL_TYPE: "default"

      SPAWN_PROTECTION: 0
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "true"
      ENABLE_COMMAND_BLOCK: "true"
      GENERATE_STRUCTURES: "true"
      MAX_BUILD_HEIGHT: 256
      SPAWN_ANIMALS: "true"
      SPAWN_MONSTERS: "true"
      SPAWN_NPCS: "true"

      CONSOLE: "false"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "testingpw"
      RCON_PORT: 28016
    restart: always
  rcon:
    container_name: "mc-rcon"
    image: itzg/rcon
    ports:
      - "4326:4326"
      - "4327:4327"
    volumes:
      - "rcon:/opt/rcon-web-admin/db"

volumes:
  mc-bukkit:
  rcon:
